# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Start deploy
        shell: bash
        run: sleep 60s

      - name: Deploy finished
        run: echo Deploying in response to ${{ github.event_name }} action ${{ github.event.action }}...
