name: Deploy

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: deployment

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - run: sleep 1m

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: sleep 1m
