name: Deploy

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

env:
  BRANCH: ${{ github.head_ref || github.ref }}
  IS_FEATURE: ${{ startsWith(github.ref, 'refs/heads/feature/') && !(contains(github.ref, 'tests')) && !(contains(github.ref, 'subtask')) }}
  IS_A_FEATURE_BRANCH: ${{ startsWith(github.ref, 'refs/heads/feature/') }}
  NOT_A_TEST_BRANCH: ${{ !(contains(github.ref, 'tests')) }}
  NOT_A_SUBTASK_BRANCH: ${{ !(contains(github.ref, 'subtask')) }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' #&& env.IS_FEATURE == 'true'
    
    steps:
      - uses: actions/checkout@v2

      - name: Start deploy
        shell: bash
        run: |
          echo Starting deployment
          printf "%q" "${{ toJSON(github) }}"

      - name: Deploy...
        shell: bash
        run: sleep 5s

      - name: Deploy finished
        run: echo Deploying in response to ${{ github.event_name }} action ${{ github.event.action }}. IsFeature = ${{ env.IS_FEATURE }}...

  destroy:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'

    steps:
      - name: Start destroy
        run: echo Calling GitHub API to invoke destroy workflow

      - name: Trigger destroy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Destroy
          token: ${{ secrets.DISPATCH_TOKEN }}
