name: Deploy

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

env:
  IS_FEATURE: ${{ startsWith(github.ref, 'refs/heads/feature/') && !(contains(github.ref, "tests") && !(contains(github.ref, "subtask"))) }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' #&& env.IS_FEATURE == 'true'
    
    steps:
      - uses: actions/checkout@v2

      - name: Start deploy
        run: echo Starting deployment

      - name: Deploy...
        shell: bash
        run: sleep 10s

      - name: Deploy finished
        run: echo Deploying in response to ${{ github.event_name }} action ${{ github.event.action }}. IsFeature = ${{ env.IS_FEATURE }}...

  destroy:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'

    steps:
      - name: Start destroy
        run: echo Calling GitHub API to invoke destroy workflow

      - name: Trigger destroy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Destroy
          token: ${{ secrets.DISPATCH_TOKEN }}
