name: Deploy

on:
  workflow_dispatch:
    inputs:
      is_ephemeral:
        description: 'Is ephemeral'
        required: true
        default: false

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      TF_VAR_IS_EPHEMERAL: ${{ github.event.inputs.is_ephemeral }}
  
    steps:
      - name: Test
        shell: bash
        run: |
          echo $TF_VAR_IS_EPHEMERAL
