name: Deploy

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize, closed, unlabeled]
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      action: ${{ steps.setup.outputs.action }}
      environment: ${{ steps.setup.outputs.environment }}

    steps:
      - id: setup
        name: Setup variables
        shell: pwsh
        env:
          ACTION: ${{ github.event.action }}
          BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.number }}
          LABEL_NAME: ${{ github.event.label.name }}
          HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'environment') }}
        run: |
          $regexResult = $env:BRANCH | Select-String -Pattern "^feature\/QP-([0-9]+)$"

          if ($regexResult) {
            $environment = "qp" + $regexResult.Matches[0].Groups[1].Value
            $isFeatureBranch = true
          } else {
            $environment = "pr" + $env:PR_NUMBER
            $isFeatureBranch = false
          }

          $labelActions = @('labeled','unlabeled')
          $destroyActions = @('unlabeled', 'closed')

          $isLabelAction = $labelActions -contains $env:ACTION
          $hasLabel = $env:HAS_LABEL -eq 'true'

          Write-Output "Environment: $environment"
          Write-Output "isLabelAction: $isLabelAction"
          Write-Output "hasLabel: $hasLabel"
          Write-Output "isFeatureBranch: $isFeatureBranch"

          if ($isLabelAction -and ($env:LABEL_NAME -ne 'environment')) {
            $action = 'none'
          } elseif (($env:ACTION -eq 'unlabeled') -or ($env:ACTION -eq 'closed' -and $hasLabel)) {
            $action = 'destroy'
          } elseif ($hasLabel -or $isLabelAction -or ($isFeatureBranch -and $env:ACTION -eq 'opened')) {
            $action = 'deploy'
          } else {
            Write-Output "else condition"
          }

          echo "::set-output name=environment::$environment"
          echo "::set-output name=action::$action"

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.action == 'deploy'
    
    steps:
      - name: Deploy
        run: |
          echo Deploying

  destroy:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.action == 'destroy'

    steps:
      - name: Destroy
        run: |
          echo Destroying