name: Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Build
        shell: bash
        run: |
          echo Hello World > output.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.txt

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: qp103
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: output

      - name: Deploy
        shell: bash
        run: |
          echo Deploying using artifacts... $(cat output.txt)
          sleep 1m
          echo Deploy finished
