name: Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - run: sleep 1m

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: deployment

    steps:
      - run: sleep 1m
