name: Deploy

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize, closed, unlabeled]
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      action: ${{ steps.setup.outputs.action }}
      environment: ${{ steps.setup.outputs.environment }}

    steps:
      - id: setup
        name: Setup variables
        shell: pwsh
        env:
          ACTION: ${{ github.event.action }}
          BRANCH: ${{ github.head_ref }}
          REF: ${{ github.ref }}
          PR_NUMBER: ${{ github.event.number }}
          LABEL_NAME: ${{ github.event.label.name }}
          HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'environment') }}
        run: |
          Write-Output "Running setup with action $env:ACTION, branch $env:BRANCH, and ref $env:REF and pr number $env:PR_NUMBER"
          Write-Output "Has label: $env:HAS_LABEL"

          $regexResult = $env:BRANCH | Select-String -Pattern "^feature\/QP-([0-9]+)$"
          
          if ($regexResult.Success) {
            $environment = "qp" + $regexResult.Matches[0].Groups[1].Value  
          } else {
            $environment = "pr" + $env:PR_NUMBER
          }

          $labelActions = @('labeled','unlabeled')
          $destroyActions = @('unlabeled', 'closed')

          if ($labelActions -contains $env:ACTION -and $env:LABEL_NAME -ne 'environment') {
            $action = 'none'
          } elseif ($destroyActions -contains $env:ACTION) {
            $action = 'destroy'
          } else {
            $action = 'deploy'
          }

          echo "::set-output name=environment::$environment"
          echo "::set-output name=action::$action"

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.action == 'deploy'
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        shell: bash
        run: |
          echo Starting deployment
          printf "%q" "${{ toJSON(github) }}"

  destroy:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.action == 'destroy'

    steps:
      - uses: actions/checkout@v2

      - name: Destroy
        run: |
          printf "%q" "${{ toJSON(github) }}"