name: Destroy

on: workflow_dispatch

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Start destroy
        run: echo Calling GitHub API to invoke destroy

      - name: Trigger destroy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.DISPATCH_TOKEN }}
          inputs: '{ "action": "destroy" }'
