name: Destroy

on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - develop

concurrency: qp101

jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    
    steps:
      - name: Destroy
        shell: bash
        run: |
          echo Destroying...
          sleep 1m
          echo Destroy finished
