# This is a basic workflow to help you get started with Actions

name: Destroy

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Destroy
        run: echo Destroying in response to ${{ github.event_name }} action ${{ github.event.action }}...

