name: Destroy

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Environment to destroy'
        required: true
        type: string

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    
    steps:
      - name: Run destroy
        run: |
          echo Destroying ${{ inputs.environment_name }}
