# This is a basic workflow to help you get started with Actions

name: Destroy

# Controls when the workflow will run
on:
  
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Start destroy
        shell: bash
        run: sleep 30s

      - name: Destroy finished
        run: echo Destroying in response to ${{ github.event_name }} action ${{ github.event.action }}...
