name: Destroy

on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - develop

jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: qp103
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Destroy
        shell: bash
        run: |
          echo Destroying...
          sleep 1m
          echo Destroy finished

      - uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ github.token }}
          environment: qp103
