name: PR

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize, closed, unlabeled]
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    outputs:
      action: ${{ steps.setup.outputs.action }}
      environment: ${{ steps.setup.outputs.environment }}

    steps:
      - id: setup
        name: Setup variables
        shell: pwsh
        env:
          ACTION: ${{ github.event.action }}
          BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.number }}
          LABEL_NAME: ${{ github.event.label.name }}
          HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'environment') }}
        run: |
          $featureBranchRegex = $env:BRANCH | Select-String -Pattern "^feature\/QP-([0-9]+)$"

          if ($featureBranchRegex) {
            $environment = "qp" + $featureBranchRegex.Matches[0].Groups[1].Value
          } else {
            $environment = "pr" + $env:PR_NUMBER
          }

          $labelActions = @('labeled','unlabeled')
          $destroyActions = @('unlabeled', 'closed')

          $isLabelAction = $labelActions -contains $env:ACTION
          $hasLabel = $env:HAS_LABEL -eq 'true'

          if ($isLabelAction -and ($env:LABEL_NAME -ne 'environment')) {
            $action = 'none'
          } elseif (($env:ACTION -eq 'unlabeled') -or ($env:ACTION -eq 'closed' -and $hasLabel)) {
            $action = 'destroy'
          } elseif ($hasLabel -or $isLabelAction -or ($featureBranchRegex -and $env:ACTION -eq 'opened')) {
            $action = 'deploy'
          } else {
            Write-Output "else condition"
          }

          echo "::set-output name=environment::$environment"
          echo "::set-output name=action::$action"

  deploy:
    name: Deploy
    needs: setup
    if: needs.setup.outputs.action == 'deploy'
    uses:  trevore-q4/actionstesting/.github/workflows/deploy.yml@${{ github.head_ref }}
    with:
      environment_name: ${{ env.environment }}

  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.action == 'destroy'
    uses: trevore-q4/actionstesting/.github/workflows/destroy.yml@${{ github.head_ref }}
    with:
      environment_name: ${{ env.environment }}
