name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.ref }}
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - run: |
          sleep 60s
          echo Done

