name: PR

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize, closed, unlabeled]
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-build
      cancel-in-progress: true

    outputs:
      action: ${{ steps.setup.outputs.action }}
      environment: ${{ steps.setup.outputs.environment }}

    steps:
      - id: setup
        name: Setup variables
        shell: pwsh
        env:
          ACTION: ${{ github.event.action }}
          BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.number }}
          LABEL_NAME: ${{ github.event.label.name }}
          HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'environment') }}
        run: |
          $featureBranchRegex = $env:BRANCH | Select-String -Pattern "^feature\/QP-([0-9]+)$"

          if ($featureBranchRegex) {
            $environment = "qp" + $featureBranchRegex.Matches[0].Groups[1].Value
          } else {
            $environment = "pr" + $env:PR_NUMBER
          }

          $labelActions = @('labeled','unlabeled')
          $destroyActions = @('unlabeled', 'closed')

          $isLabelAction = $labelActions -contains $env:ACTION
          $hasLabel = $env:HAS_LABEL -eq 'true'

          if ($isLabelAction -and ($env:LABEL_NAME -ne 'environment')) {
            $action = 'none'
          } elseif (($env:ACTION -eq 'unlabeled') -or ($env:ACTION -eq 'closed' -and $hasLabel)) {
            $action = 'destroy'
          } elseif ($hasLabel -or $isLabelAction -or ($featureBranchRegex -and $env:ACTION -eq 'opened')) {
            $action = 'deploy'
          }

          echo "::set-output name=environment::$environment"
          echo "::set-output name=action::$action"

      - id: build
        name: Build
        shell: bash
        run: |
          echo Building...
          sleep 60s
          echo Build finished

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.action != ''
    concurrency:
      group: ${{ github.ref }}-deploy
      cancel-in-progress: false
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        if: needs.build.outputs.action == 'deploy'
        uses: ./.github/actions/deploy
        with:
          environment_name: ${{ needs.build.outputs.environment }}

      - name: Destroy
        if: needs.build.outputs.action == 'destroy'
        uses: ./.github/actions/destroy
        with:
          environment_name: ${{ needs.build.outputs.environment }}
