name: Test

on:
  workflow_dispatch:
    inputs:
      is_ephemeral:
        description: 'Is ephemeral'
        required: true
        default: false

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      TF_VAR_IS_EPHEMERAL: ${{ github.event.inputs.is_ephemeral }}
  
    steps:
      - uses: actions/checkout@v2

      - id: test
        name: Test
        uses: ./.github/actions/test
        with:
          is_ephemeral: inputs.is_ephemeral
