name: Test

on:
  workflow_dispatch:

jobs:
  test_not_ephemeral:
    name: Test Not Ephemeral
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Test not ephemeral
        uses: ./.github/actions/test
        with:
          is_ephemeral: false

  test_ephemeral:
    name: Test Ephemeral
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Test ephemeral
        uses: ./.github/actions/test
        with:
          is_ephemeral: true
