name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          MY_ENV_VAR: my env var value
          MY_OTHER_ENV_VAR: false

      - name: Print env vars
        shell: bash
        run: |
          echo $MY_ENV_VAR
          echo $MY_OTHER_ENV_VAR
