name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      TF_VAR_IS_EPHEMERAL: ${{ github.event.inputs.is_ephemeral }}
  
    steps:
      - uses: actions/checkout@v2

      - name: Test not ephemeral
        uses: ./.github/actions/test
        with:
          is_ephemeral: false

      - name: Test ephemeral
        uses: ./.github/actions/test
        with:
          is_ephemeral: true
