name: Test

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
  
    steps:
      - run: sleep 1m

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event.action != 'closed'
    concurrency:
      group: deployment

    steps:
      - run: sleep 1m

  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    concurrency:
      group: deployment

    steps:
      - run: sleep 1m
