name: Test

on: push

jobs:
  des:
    name: Test
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/test
        with:
          continue-on-error: true
